// Authored metadata fixtures only; no captured evidence.
import type { Hit, PlacesResponse, SearchResponse } from "../api/schema";
export const hit: Hit = {
  id: "00000000-0000-0000-0000-000000000001",
  source_sha256: "a".repeat(64),
  address: "192.0.2.1",
  port: 80,
  transport: "tcp",
  outcome: "open",
  finished_at: "2026-10-04T12:00:00Z",
  started_at: "2026-10-04T11:59:59Z",
  has_evidence: true,
  fresh: true,
  derivation_id: "b".repeat(64),
  enrichment_id: "c".repeat(64),
  category_state: "multiple",
  geography_state: "known",
  network: { prefix: "192.0.2.0/24", origin: "fixture", asns: [64496, 64497] },
  place: {
    id: "fixture:east",
    name: "Example Harbor",
    country_code: "FJ",
    point: [179.5, -17.5],
  },
  city: {
    prefix: "192.0.2.0/24",
    origin: "fixture",
    place_id: "fixture:east",
    accuracy_radius_km: null,
    radius_basis: "unknown",
  },
  candidate_count: 2,
  products: ['<img src="https://hostile.invalid/x" onerror="alert(1)">\u202E'],
  categories: ["web_server", "router"],
};
export const response: SearchResponse = {
  selection: {
    mode: "current",
    selection: "attempt",
    as_of: "2026-10-04T12:00:00Z",
    pack_sha256: "f".repeat(64),
    dataset_sha256: "d".repeat(64),
  },
  retention_checked_at: "2026-10-04T12:00:00Z",
  dataset_checked_at: "2026-10-04T12:00:00Z",
  pack: null,
  dataset: {
    schema_version: 1,
    id: "fixture",
    version: "1.0.0",
    valid_from: "2026-10-01T00:00:00Z",
    expires_at: "2026-11-01T00:00:00Z",
    origins: [
      {
        id: "fixture",
        version: "1",
        source_url: "javascript:alert(1)",
        source_sha256: "e".repeat(64),
        license: "Authored fixture",
        license_url: "https://hostile.invalid/license",
        attribution: "Synthetic attribution",
        modifications: "Fictional data",
      },
    ],
  },
  counts: { endpoints: 2, observations: 2, candidates: 4 },
  facets: [
    {
      kind: "category",
      value: "web_server",
      endpoints: 2,
      observations: 2,
      rank: 1,
      total_buckets: 3,
    },
  ],
  hits: [hit],
  next_cursor: "opaque-first-query",
};
export const places: PlacesResponse = {
  dataset_sha256: "d".repeat(64),
  dataset: response.dataset as NonNullable<SearchResponse["dataset"]>,
  dataset_state: "valid",
  retention_checked_at: response.retention_checked_at,
  total: 2,
  places: ["east", "west"].map((part) => ({
    id: `fixture:${part}`,
    origin: "fixture",
    name: "Example Harbor",
    country_code: "FJ",
    admin_code: part,
    kind: "city",
    point: null,
    boundary_kind: null,
    has_boundary: false,
  })),
};
