// Generated by python -m netatlas.read_api.contract; do not edit.
// OpenAPI SHA-256: e4a46454b7544ca8cbf5cfb63e6d860c410566b9b50a0b613992b7c1afc0a4f9

export type AsnPrefix = {
  "prefix": string;
  "origin": string;
  "asns": ReadonlyArray<number>;
  "organization"?: string | null;
};

export type Box = {
  "west": number;
  "south": number;
  "east": number;
  "north": number;
};

export type Category = "unknown" | "web_server" | "camera_nvr" | "router" | "nas" | "printer" | "ssh_server" | "vpn_appliance" | "mail_server" | "database" | "iot" | "industrial";

export type CityPrefix = {
  "prefix": string;
  "origin": string;
  "place_id": string;
  "accuracy_radius_km"?: number | null;
  "radius_basis"?: "dataset_reported" | "unknown";
};

export type Counts = {
  "endpoints": number;
  "observations": number;
  "candidates": number;
};

export type DatasetMetadata = {
  "schema_version": 1;
  "id": string;
  "version": string;
  "valid_from": string;
  "expires_at": string;
  "origins": ReadonlyArray<Origin>;
};

export type EndpointQuery = {
  "selection"?: "attempt" | "open" | "evidence";
  "as_of"?: string | null;
  "pack_sha256"?: string | null;
  "dataset_sha256"?: string | null;
  "fingerprint_engine"?: "fingerprints-1";
  "taxonomy"?: "netatlas-categories-1";
  "enrichment_engine"?: "enrichment-1";
  "fresh_seconds"?: number;
  "limit"?: number;
};

export type EndpointRequest = {
  "schema_version": 1;
  "query"?: EndpointQuery;
  "cursor"?: string | null;
};

export type Error = {
  "code": "invalid_request" | "invalid_cursor" | "cursor_expired" | "not_found" | "forbidden" | "too_large" | "unsupported_media_type" | "request_timeout" | "busy" | "unavailable" | "response_too_large" | "internal_error" | "method_not_allowed";
};

export type ErrorResponse = {
  "error": Error;
};

export type Facet = {
  "kind": "category" | "asn" | "country" | "prefix" | "geography";
  "value": string;
  "endpoints": number;
  "observations": number;
  "rank": number;
  "total_buckets": number;
};

export type Hit = {
  "id": string;
  "source_sha256": string;
  "address": string;
  "port": number;
  "transport": "tcp" | "udp";
  "outcome": "open" | "closed" | "timeout" | "error";
  "finished_at": string;
  "started_at": string;
  "has_evidence": boolean;
  "fresh": boolean;
  "derivation_id": string | null;
  "enrichment_id": string | null;
  "category_state": "unknown" | "single" | "multiple";
  "geography_state": "known" | "unknown" | "stale" | "not_yet_valid";
  "network": AsnPrefix | null;
  "place": HitPlace | null;
  "city": CityPrefix | null;
  "candidate_count": number;
  "products": ReadonlyArray<string>;
  "categories": ReadonlyArray<Category>;
};

export type HitPlace = {
  "id": string;
  "name": string;
  "country_code": string;
  "point": readonly [number, number] | null;
};

export type Origin = {
  "id": string;
  "version": string;
  "source_url": string;
  "source_sha256": string;
  "license": string;
  "license_url": string;
  "attribution": string;
  "modifications": string;
};

export type PackMetadata = {
  "schema_version": 1;
  "pack_id": string;
  "version": string;
  "taxonomy_version": "netatlas-categories-1";
  "provenance": string;
};

export type PlaceSummary = {
  "id": string;
  "origin": string;
  "name": string;
  "country_code": string;
  "admin_code": string | null;
  "kind": "city" | "country" | "region";
  "point": readonly [number, number] | null;
  "boundary_kind": "generalized" | "synthetic" | null;
  "has_boundary": boolean;
};

export type PlacesQuery = {
  "dataset_sha256": string;
  "name"?: string | null;
  "country"?: string | null;
  "kind"?: "city" | "region" | "country" | null;
  "limit"?: number;
};

export type PlacesRequest = {
  "schema_version": 1;
  "query": PlacesQuery;
  "cursor"?: string | null;
};

export type PlacesResponse = {
  "schema_version"?: 1;
  "dataset_sha256": string;
  "dataset": DatasetMetadata;
  "dataset_state": "valid" | "stale" | "not_yet_valid";
  "retention_checked_at": string;
  "places": ReadonlyArray<PlaceSummary>;
  "total": number;
  "next_cursor"?: string | null;
  "location_semantics"?: "approximate_area_not_person_or_device";
};

export type Radius = {
  "longitude": number;
  "latitude": number;
  "metres": number;
};

export type SearchMetadata = {
  "schema_version"?: 1;
  "selection": SearchQuery;
  "retention_checked_at": string;
  "dataset_checked_at": string;
  "dataset": DatasetMetadata | null;
  "pack": PackMetadata | null;
  "counts": Counts;
  "facets": ReadonlyArray<Facet>;
  "location_semantics"?: "approximate_area_not_person_or_device";
  "count_semantics"?: "selected_retained_observations_not_devices_or_prevalence";
};

export type SearchQuery = {
  "schema_version"?: 1;
  "mode"?: "current" | "history";
  "selection"?: "attempt" | "open" | "evidence";
  "as_of"?: string | null;
  "after"?: string | null;
  "before"?: string | null;
  "freshness"?: "any" | "fresh" | "stale";
  "fresh_seconds"?: number;
  "network"?: string | null;
  "port"?: number | null;
  "transport"?: "tcp" | "udp" | null;
  "outcome"?: "open" | "closed" | "timeout" | "error" | null;
  "has_evidence"?: boolean | null;
  "category"?: Category | null;
  "text"?: string | null;
  "pack_sha256"?: string | null;
  "fingerprint_engine"?: "fingerprints-1";
  "taxonomy"?: "netatlas-categories-1";
  "dataset_sha256"?: string | null;
  "enrichment_engine"?: "enrichment-1";
  "asn"?: number | null;
  "country"?: string | null;
  "place_id"?: string | null;
  "geography"?: "any" | "known" | "unknown" | "stale" | "not_yet_valid";
  "radius"?: Radius | null;
  "box"?: Box | null;
  "boundary_place_id"?: string | null;
  "limit"?: number;
  "offset"?: 0;
  "facet_limit"?: number;
};

export type SearchRequest = {
  "schema_version": 1;
  "query"?: SearchQuery;
  "cursor"?: string | null;
};

export type SearchResponse = {
  "schema_version"?: 1;
  "selection": SearchQuery;
  "retention_checked_at": string;
  "dataset_checked_at": string;
  "dataset": DatasetMetadata | null;
  "pack": PackMetadata | null;
  "counts": Counts;
  "facets": ReadonlyArray<Facet>;
  "location_semantics"?: "approximate_area_not_person_or_device";
  "count_semantics"?: "selected_retained_observations_not_devices_or_prevalence";
  "hits": ReadonlyArray<Hit>;
  "next_cursor"?: string | null;
  "page_limit_reached"?: boolean;
};

export interface Operations {
  endpointDetail: { request: EndpointRequest; response: SearchResponse };
  endpointHistory: { request: EndpointRequest; response: SearchResponse };
  facets: { request: SearchRequest; response: SearchMetadata };
  places: { request: PlacesRequest; response: PlacesResponse };
  search: { request: SearchRequest; response: SearchResponse };
}

export const routes = {
  "endpointDetail": "/api/v1/endpoints/{address}/{transport}/{port}/detail",
  "endpointHistory": "/api/v1/endpoints/{address}/{transport}/{port}/history",
  "facets": "/api/v1/facets",
  "places": "/api/v1/places",
  "search": "/api/v1/search"
} as const;

export const errorCodes = ["invalid_request", "invalid_cursor", "cursor_expired", "not_found", "forbidden", "too_large", "unsupported_media_type", "request_timeout", "busy", "unavailable", "response_too_large", "internal_error", "method_not_allowed"] as const;
