"""Generate the small read-client type surface directly from FastAPI's OpenAPI.

Unsupported schema shapes fail generation. A schema digest also detects drift in
constraints that TypeScript cannot express. No database or network is opened.
"""

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from netatlas.api import create_app

OPERATIONS = {
    "search",
    "facets",
    "places",
    "endpointDetail",
    "endpointHistory",
    "endpointInspection",
}
DESTINATION = Path("web/src/api/schema.ts")


def generate() -> str:
    schema = create_app().openapi()
    definitions = schema["components"]["schemas"]
    used: set[str] = set()

    def ts(item: dict[str, Any]) -> str:
        if "$ref" in item:
            name = str(item["$ref"]).split("/")[-1]
            used.add(name)
            return name.replace("-", "_")
        if "const" in item:
            return json.dumps(item["const"])
        if "enum" in item:
            return " | ".join(json.dumps(x) for x in item["enum"])
        if "anyOf" in item:
            return " | ".join(ts(x) for x in item["anyOf"])
        match item.get("type"):
            case "string":
                return "string"
            case "integer" | "number":
                return "number"
            case "boolean":
                return "boolean"
            case "null":
                return "null"
            case "array":
                if "prefixItems" in item:
                    return "readonly [" + ", ".join(ts(x) for x in item["prefixItems"]) + "]"
                return f"ReadonlyArray<{ts(item['items'])}>"
            case "object":
                props = item.get("properties", {})
                required = item.get("required", [])
                if item.get("additionalProperties") not in (None, False):
                    raise ValueError("unreviewed open object")
                return (
                    "{\n"
                    + "\n".join(
                        f"  {json.dumps(key)}{'' if key in required else '?'}: {ts(value)};"
                        for key, value in props.items()
                    )
                    + "\n}"
                )
            case _:
                raise ValueError("unsupported OpenAPI schema")

    operations = {}
    for path, methods in schema["paths"].items():
        for operation in methods.values():
            name = operation["operationId"]
            if name in OPERATIONS:
                request = ts(operation["requestBody"]["content"]["application/json"]["schema"])
                response = ts(
                    operation["responses"]["200"]["content"]["application/json"]["schema"]
                )
                operations[name] = (request, response, path)
    used.add("ErrorResponse")
    rendered: dict[str, str] = {}
    while used - rendered.keys():
        for name in sorted(used - rendered.keys()):
            rendered[name] = f"export type {name.replace('-', '_')} = {ts(definitions[name])};\n"
    digest = hashlib.sha256(json.dumps(schema, sort_keys=True).encode()).hexdigest()
    return (
        "// Generated by python -m netatlas.read_api.contract; do not edit.\n"
        f"// OpenAPI SHA-256: {digest}\n\n"
        + "\n".join(rendered[n] for n in sorted(rendered))
        + "\nexport interface Operations {\n"
        + "\n".join(
            f"  {name}: {{ request: {req}; response: {res} }};"
            for name, (req, res, _) in sorted(operations.items())
        )
        + "\n}\n"
        + "\nexport const routes = "
        + json.dumps({name: path for name, (_, _, path) in sorted(operations.items())}, indent=2)
        + " as const;\n"
        + "\nexport const errorCodes = "
        + json.dumps(definitions["Error"]["properties"]["code"]["enum"])
        + " as const;\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = generate()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != output:
            parser.exit(1, "Read client contract differs; regenerate it.\n")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_text(output)


if __name__ == "__main__":
    main()
